[build]
publish = ".deploy_git"
command = "hexo deploy"

[build.environment]
NODE_VERSION = "16"

[[redirects]]
from = "/.well-known/*"
to = "/.well-known/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
